refactor: CI/CD 파이프라인 비활성화
- Actions 횟수 차감 방지를 위한 CI/CD 파일 주석 처리

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -1,95 +1,95 @@
-name: CD - Deploy(Blue/Green) to EC2
-
-on:
-  workflow_run:
-    workflows: [ "CI - Build and Push to Docker Hub" ]
-    types:
-      - completed
-    branches:
-      - main
-
-env:
-  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/cream
-
-jobs:
-  deploy:
-    runs-on: ubuntu-22.04
-    if: ${{ github.event.workflow_run.conclusion == 'success' }}
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set Image Tag from Workflow Run
-        run: |
-          echo "IMAGE_TAG=sha-${{ github.event.workflow_run.head_sha }}" >> $GITHUB_ENV
-
-      - name: Transfer docker-compose-app.yml to EC2
-        uses: appleboy/scp-action@v0.1.7
-        with:
-          host: ${{ secrets.EC2_PUBLIC_IP }}
-          username: ${{ secrets.EC2_USERNAME }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          source: "docker-compose-app.yml"
-          target: "~/"
-
-      - name: Deploy to Public EC2(inactive container)
-        uses: appleboy/ssh-action@v1.0.3
-        with:
-          host: ${{ secrets.EC2_PUBLIC_IP }}
-          username: ${{ secrets.EC2_USERNAME }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          script: |
-            CURRENT_PORT=$(cat /etc/nginx/conf.d/service-url.inc | grep -oP ':\K[0-9]+(?=;)' | tr -d '\n')
-            
-            if [ "${CURRENT_PORT}" == "8081" ]; then
-              NEXT_NAME="green"
-              NEXT_PORT="8082"
-            else
-              NEXT_NAME="blue"
-              NEXT_PORT="8081"
-            fi
-            
-            DEPLOY_SERVICE_NAME="spring-app-${NEXT_NAME}"
-            
-            cat > .env << EOF
-            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
-            IMAGE_TAG=${{ env.IMAGE_TAG }}
-            DB_HOST=${{ secrets.PRIVATE_DB_HOST }}
-            REDIS_HOST=${{ secrets.PRIVATE_REDIS_HOST }}
-            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
-            DB_USERNAME=${{ secrets.DB_USERNAME }}
-            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
-            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
-            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
-            PORTONE_STORE_ID=${{ secrets.PORTONE_STORE_ID }}
-            PORTONE_API_SECRET=${{ secrets.PORTONE_API_SECRET }}
-            PORTONE_CHANNEL_KEY=${{ secrets.PORTONE_CHANNEL_KEY }}
-            AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
-            AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
-            BUCKET_NAME=${{ secrets.BUCKET_NAME }}
-            AWS_REGION=${{ secrets.AWS_REGION }}
-            EOF
-            
-            mv docker-compose-app.yml docker-compose.yml
-
-            docker-compose pull ${DEPLOY_SERVICE_NAME}
-            docker-compose up -d ${DEPLOY_SERVICE_NAME}
-            
-            for i in $(seq 1 10); do
-            if curl -f http://127.0.0.1:${NEXT_PORT}/actuator/health > /dev/null; then
-            echo "Health check passed"
-            break
-            fi
-            if [ $i -eq 10 ]; then
-            echo "Health check failed"
-            exit 1
-            fi
-            sleep 10
-            done
-
-            echo "set \$service_url http://127.0.0.1:${NEXT_PORT};" | sudo tee /etc/nginx/conf.d/service-url.inc
-            sudo nginx -t
-            sudo nginx -s reload
-            
-            docker image prune -f
+#name: CD - Deploy(Blue/Green) to EC2
+#
+#on:
+#  workflow_run:
+#    workflows: [ "CI - Build and Push to Docker Hub" ]
+#    types:
+#      - completed
+#    branches:
+#      - main
+#
+#env:
+#  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/cream
+#
+#jobs:
+#  deploy:
+#    runs-on: ubuntu-22.04
+#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
+#
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#
+#      - name: Set Image Tag from Workflow Run
+#        run: |
+#          echo "IMAGE_TAG=sha-${{ github.event.workflow_run.head_sha }}" >> $GITHUB_ENV
+#
+#      - name: Transfer docker-compose-app.yml to EC2
+#        uses: appleboy/scp-action@v0.1.7
+#        with:
+#          host: ${{ secrets.EC2_PUBLIC_IP }}
+#          username: ${{ secrets.EC2_USERNAME }}
+#          key: ${{ secrets.EC2_SSH_KEY }}
+#          source: "docker-compose-app.yml"
+#          target: "~/"
+#
+#      - name: Deploy to Public EC2(inactive container)
+#        uses: appleboy/ssh-action@v1.0.3
+#        with:
+#          host: ${{ secrets.EC2_PUBLIC_IP }}
+#          username: ${{ secrets.EC2_USERNAME }}
+#          key: ${{ secrets.EC2_SSH_KEY }}
+#          script: |
+#            CURRENT_PORT=$(cat /etc/nginx/conf.d/service-url.inc | grep -oP ':\K[0-9]+(?=;)' | tr -d '\n')
+#
+#            if [ "${CURRENT_PORT}" == "8081" ]; then
+#              NEXT_NAME="green"
+#              NEXT_PORT="8082"
+#            else
+#              NEXT_NAME="blue"
+#              NEXT_PORT="8081"
+#            fi
+#
+#            DEPLOY_SERVICE_NAME="spring-app-${NEXT_NAME}"
+#
+#            cat > .env << EOF
+#            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
+#            IMAGE_TAG=${{ env.IMAGE_TAG }}
+#            DB_HOST=${{ secrets.PRIVATE_DB_HOST }}
+#            REDIS_HOST=${{ secrets.PRIVATE_REDIS_HOST }}
+#            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
+#            DB_USERNAME=${{ secrets.DB_USERNAME }}
+#            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
+#            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
+#            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
+#            PORTONE_STORE_ID=${{ secrets.PORTONE_STORE_ID }}
+#            PORTONE_API_SECRET=${{ secrets.PORTONE_API_SECRET }}
+#            PORTONE_CHANNEL_KEY=${{ secrets.PORTONE_CHANNEL_KEY }}
+#            AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
+#            AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
+#            BUCKET_NAME=${{ secrets.BUCKET_NAME }}
+#            AWS_REGION=${{ secrets.AWS_REGION }}
+#            EOF
+#
+#            mv docker-compose-app.yml docker-compose.yml
+#
+#            docker-compose pull ${DEPLOY_SERVICE_NAME}
+#            docker-compose up -d ${DEPLOY_SERVICE_NAME}
+#
+#            for i in $(seq 1 10); do
+#            if curl -f http://127.0.0.1:${NEXT_PORT}/actuator/health > /dev/null; then
+#            echo "Health check passed"
+#            break
+#            fi
+#            if [ $i -eq 10 ]; then
+#            echo "Health check failed"
+#            exit 1
+#            fi
+#            sleep 10
+#            done
+#
+#            echo "set \$service_url http://127.0.0.1:${NEXT_PORT};" | sudo tee /etc/nginx/conf.d/service-url.inc
+#            sudo nginx -t
+#            sudo nginx -s reload
+#
+#            docker image prune -f
